{{ docker.from("bootstrap", "ubuntu-16.04") }}

{{ docker.version() }}

{{ environment.base() }}

{{ docker.copy('conf/', '/opt/docker/') }}

{{ ansible.ubuntu() }}

{{ base.ubuntu() }}

{{ docker.entrypoint("/opt/docker/bin/entrypoint.sh") }}
{{ docker.cmd("supervisord") }}
