{{ docker.from("php-dev", "ubuntu-15.04") }}

{{ docker.version() }}

{{ environment.web() }}
{{ environment.webPhp() }}
{{ environment.webDevelopment() }}

{{ docker.copy('conf/', '/opt/docker/') }}

{{ apache.ubuntu15('php-apache') }}

{{ docker.expose('80 443') }}
