{{ docker.from("php-apache", "ubuntu-15.04") }}

{{ environment.web() }}
{{ environment.webPhp() }}
{{ environment.webDevelopment() }}

{{ docker.copy('conf/', '/opt/docker/') }}

{{ apache.ubuntu15('php-apache apache-dev php-dev') }}

{{ docker.expose('80 443') }}
