{{ docker.from("php-apache", "ubuntu-15.10") }}

{{ environment.web() }}
{{ environment.webPhp() }}
{{ environment.webDevelopment() }}

{{ docker.copy('conf/', '/opt/docker/') }}

{{ php5dev.ubuntu() }}
