{{ docker.from("php-apache", "debian-8-php7") }}

{{ environment.web() }}
{{ environment.webPhp() }}
{{ environment.webDevelopment() }}

{{ docker.copy('conf/', '/opt/docker/') }}

{{ php7dev.debianSury() }}
