{{ docker.from("php-dev", "debian-8-php7") }}

{{ docker.version() }}

{{ environment.web() }}

{{ docker.copy('conf/', '/opt/docker/') }}

{{ apache.debian8('php-apache') }}

{{ docker.expose('80 443') }}
