#++++++++++++++++++++++++++++++++++++++
# CentOS 7 Ansible Docker container
#++++++++++++++++++++++++++++++++++++++

FROM webdevops/bootstrap:centos-7
MAINTAINER info@webdevops.io
LABEL vendor=WebDevOps.io
LABEL io.webdevops.layout=6
LABEL io.webdevops.version=0.21.0
