{{ docker.fromOfficial("php", "5.6-fpm") }}

{{ docker.version() }}

{{ environment.general() }}
{{ environment.app() }}

{{ docker.add('baselayout.tar', '/') }}

{{ docker.copy('conf/', '/opt/docker/') }}

{{ bootstrap.debian('jessie') }}

{{ ansible.debian() }}

{{ base.debian() }}

{{ baseapp.debian() }}

{{ php.official() }}

{{ docker.expose('9000') }}
{{ docker.entrypoint("/opt/docker/bin/entrypoint.sh") }}
{{ docker.cmd("supervisord") }}
