{{ docker.from("bootstrap","ubuntu-16.04") }}

RUN apt-install \
        build-essential \
        apt-transport-https \
        ca-certificates \
        curl \
        software-properties-common \
        python \
        python-dev \
        python-setuptools \
        python-pip \
        graphviz \
        ruby \
        ruby-dev \
        ruby-bundler \
    && curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add - \
    && add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu    $(lsb_release -cs)    stable" \
    && apt-install docker-ce \
    && curl -LO https://storage.googleapis.com/container-structure-test/latest/container-structure-test-linux-amd64 \
    && chmod +x container-structure-test-linux-amd64 \
    && sudo mv container-structure-test-linux-amd64 /usr/local/bin/container-structure-test \
    && pip install --upgrade pip \
    && hash -r pip \
    && pip install --upgrade setuptools \
    && pip install --upgrade \
        MarkupSafe \
        Jinja2 \
        graphviz \
        funcsigs \
        pbr \
        six \
        mock \
        psutil \
        pylev \
        py \
        appdirs \
        pyparsing \
        packaging \
        pytest \
        simplejson \
        backpack \
        cleo \
        pyyaml \
        yamlordereddictloader \
        testinfra \
        cloudpickle \
        pyinotify \
        configparser \
        doit==0.29.0 \
        termcolor \
        pytest-timeout \
        pytest-rerunfailures \
    {{ docker.cleanup() }}
