{{ docker.from("php", "ubuntu-16.04") }}

{{ docker.version() }}

{{ environment.web() }}
{{ environment.webPhp() }}

{{ docker.copy('conf/', '/opt/docker/') }}

{{ nginx.ubuntu('php-nginx') }}

{{ docker.expose('80 443') }}
