{{ docker.from("php", "ubuntu-15.10") }}

{{ environment.web() }}
{{ environment.webPhp() }}

{{ docker.copy('conf/', '/opt/docker/') }}

{{ apache.ubuntu16('php-apache') }}

{{ docker.expose('80 443') }}
