#FROM webdevops/base:centos-7
#FROM webdevops/base:debian-8
#FROM webdevops/base:ubuntu-12.04
#FROM webdevops/base:ubuntu-14.04
#FROM webdevops/base:ubuntu-15.04
#FROM webdevops/base:ubuntu-15.10

#FROM webdevops/php:centos-7
#FROM webdevops/php:debian-8
#FROM webdevops/php:ubuntu-12.04
#FROM webdevops/php:ubuntu-14.04
#FROM webdevops/php:ubuntu-15.04
#FROM webdevops/php:ubuntu-15.10

#FROM webdevops/php-apache:centos-7
#FROM webdevops/php-apache:debian-8
#FROM webdevops/php-apache:ubuntu-12.04
#FROM webdevops/php-apache:ubuntu-14.04
#FROM webdevops/php-apache:ubuntu-15.04
#FROM webdevops/php-apache:ubuntu-15.10

#FROM webdevops/php-nginx:centos-7
#FROM webdevops/php-nginx:debian-8
#FROM webdevops/php-nginx:ubuntu-12.04
#FROM webdevops/php-nginx:ubuntu-14.04
#FROM webdevops/php-nginx:ubuntu-15.04
#FROM webdevops/php-nginx:ubuntu-15.10

#FROM webdevops/hhvm-apache
#FROM webdevops/hhvm-nginx

#FROM webdevops/postfix
#FROM webdevops/ssh
#FROM webdevops/storage
#FROM webdevops/vsftp
