{{ docker.from("php-nginx") }}

{{ environment.mailbox() }}

{{ docker.copy('conf/', '/opt/docker/') }}

{{ mailsandbox.ubuntu() }}

{{ mailsandbox.roundcube() }}

{{ docker.expose('25 465 587 143 993') }}
