{{ docker.from("php", "alpine-3-php7") }}

{{ environment.web() }}
{{ environment.webPhp() }}

{{ docker.copy('conf/', '/opt/docker/') }}

{{ nginx.alpine('php-nginx') }}

{{ docker.expose('80 443') }}
