{{ docker.from("php-apache", "ubuntu-14.04") }}

ENV WEB_DOCUMENT_ROOT /app/web/

{{ docker.copy('conf/', '/opt/docker/') }}

ONBUILD RUN composer create-project typo3/cms-base-distribution /app/
ONBUILD VOLUME /app
