{{ docker.from("php-dev", "centos-7-php7") }}

{{ environment.web() }}
{{ environment.webPhp() }}
{{ environment.webDevelopment() }}

{{ docker.copy('conf/', '/opt/docker/') }}

{{ apache.centos('php-apache apache-dev php-dev') }}

{{ docker.expose('80 443') }}
