---

- name: Filesystem cleanup [Debian family]
  file:
    path: "{{ item }}"
    state: absent
  with_fileglob:
    - /var/cache/apt/archives/*.deb
    - /var/cache/apt/archives/partial/*
    - /var/cache/debconf/*-old
    - /var/lib/apt/lists/*
  when: ansible_os_family == "Debian"

- name: Yum cleanup [RedHat family]
  command: yum clean all
  when: ansible_os_family == "RedHat"
