{{ docker.from("php-dev", "alpine-php5") }}

{{ environment.web() }}
{{ environment.webPhp() }}
{{ environment.webDevelopment() }}

{{ docker.copy('conf/', '/opt/docker/') }}

{{ apache.alpine('php-apache apache-dev php-dev') }}

{{ docker.expose('80 443') }}
