{{ docker.from("php", "centos-7-php56") }}

{{ docker.version() }}

{{ docker.environmentWeb() }}

{{ docker.copy('conf/', '/opt/docker/') }}

{{ nginx.centos('php-nginx') }}

{{ docker.expose('80 443') }}
