{{ docker.from("base-app", "ubuntu-18.04") }}

{{ docker.copy('conf/', '/opt/docker/') }}

RUN set -x \
    {{ php7.ubuntu(phpVersion='7.2') }} \
    {{ provision.runBootstrap() }} \
    {{ docker.cleanup() }}

{{ docker.expose('9000') }}
