{{ docker.from("php-dev", "centos-7") }}

{{ docker.version() }}

{{ environment.web() }}

{{ docker.copy('conf/', '/opt/docker/') }}

{{ apache.centos('php-apache') }}

{{ docker.expose('80 443') }}
