{{ docker.from("php-dev", "centos-7") }}

{{ docker.version() }}

{{ environment.web() }}
{{ environment.webPhp() }}
{{ environment.webDevelopment() }}

{{ docker.copy('conf/', '/opt/docker/') }}

{{ apache.centos('php-apache php-apache-dev') }}

{{ docker.expose('80 443') }}
