{{ docker.from("php-apache", "alpine-php7") }}

{{ environment.web() }}
{{ environment.webPhp() }}
{{ environment.webDevelopment() }}

{{ docker.copy('conf/', '/opt/docker/') }}

RUN set -x \
    {{ php7dev.alpine() }} \
    {{ provision.runBootstrap() }} \
    {{ docker.cleanup() }}
