{{ docker.from("php-dev", "debian-9") }}

{{ environment.web() }}
{{ environment.webPhp() }}
{{ environment.webDevelopment() }}

{{ docker.copy('conf/', '/opt/docker/') }}

{{ apache.debian9('php-apache apache-dev php-dev') }}

{{ docker.expose('80 443') }}
