{{ docker.from("php-dev", "debian-9") }}

{{ docker.version() }}

{{ environment.web() }}
{{ environment.webPhp() }}
{{ environment.webDevelopment() }}

{{ docker.copy('conf/', '/opt/docker/') }}

{{ apache.debian9('php-apache php-apache-dev') }}

{{ docker.expose('80 443') }}
