#++++++++++++++++++++++++++++++++++++++
# Ubuntu 14.04 Ansible Docker container
#++++++++++++++++++++++++++++++++++++++

FROM webdevops/bootstrap:ubuntu-14.04
MAINTAINER info@webdevops.io
LABEL vendor=WebDevOps.io
LABEL io.webdevops.layout=6
LABEL io.webdevops.version=0.23.0
