{{ docker.from("base-app", "debian-9") }}

{{ environment.web() }}
{{ environment.phpComposerVersion() }}

{{ docker.copy('conf/', '/opt/docker/') }}

RUN set -x \
    {{ php7.debian9() }} \
    {{ provision.runBootstrap() }} \
    {{ docker.cleanup() }}

{{ docker.expose('9000') }}
