production:
  adapter: sqlite3
  database: /storage/db/database.sqlite3
  pool: 5
  timeout: 5000

staging:
  adapter: sqlite3
  database: /storage/db/database.sqlite3
  pool: 5
  timeout: 5000

development:
  adapter: sqlite3
  database: /storage/db/database.sqlite3
  pool: 5
  timeout: 5000

test:
  adapter: sqlite3
  database: /storage/db/database.sqlite3
  pool: 5
  timeout: 5000
