{{ base.from("base", "debian-8") }}

{{ base.version() }}

{{ base.environmentWeb() }}

{{ nginx.debian() }}

# Deploy scripts/configurations
COPY conf/ /opt/docker/
RUN bash /opt/docker/bin/control.sh provision.role.bootstrap webdevops-nginx \
    && bash /opt/docker/bin/bootstrap.sh

EXPOSE 80 443

CMD ["supervisord"]
