{{ docker.from("php", "7.0") }}

{{ docker.version() }}

{{ environment.web() }}
{{ environment.webPhp() }}

{{ docker.copy('conf/', '/opt/docker/') }}

{{ nginx.debian('php-nginx') }}

{{ docker.expose('80 443') }}
