#++++++++++++++++++++++++++++++++++++++
# Ubuntu 15.10 Ansible Docker container
#++++++++++++++++++++++++++++++++++++++

FROM webdevops/bootstrap:ubuntu-15.10
MAINTAINER info@webdevops.io
LABEL vendor=WebDevOps.io
LABEL io.webdevops.layout=4
LABEL io.webdevops.version=0.19.0
