{{ docker.from("php-dev", "5.6") }}

{{ docker.version() }}

{{ environment.web() }}
{{ environment.webPhp() }}
{{ environment.webDevelopment() }}

{{ docker.copy('conf/', '/opt/docker/') }}

{{ nginx.debian('php-nginx nginx-dev php-dev') }}

{{ docker.expose('80 443') }}
