{{ docker.from("php-nginx", "5.6") }}

{{ environment.web() }}
{{ environment.webPhp() }}
{{ environment.webDevelopment() }}

{{ docker.copy('conf/', '/opt/docker/') }}

{{ php.officialDevelopment(version="5.6") }}
