#++++++++++++++++++++++++++++++++++++++
# Debian 7 PHP Docker container
#++++++++++++++++++++++++++++++++++++++

FROM webdevops/base:debian-7
MAINTAINER info@webdevops.io

ENV WEB_DOCUMENT_ROOT  /app

# Install dotdeb
RUN echo "deb http://packages.dotdeb.org wheezy all" >> /etc/apt/sources.list \
    && echo "deb-src http://packages.dotdeb.org wheezy all" >> /etc/apt/sources.list \
    && wget wget -O- https://www.dotdeb.org/dotdeb.gpg | apt-key add  -

# Install tools
RUN /usr/local/bin/apt-install \
        imagemagick \
    graphviz 

COPY conf/ /opt/docker/
RUN bash /opt/docker/bin/control.sh provision.role.bootstrap webdevops-php-dev \
    && bash /opt/docker/bin/bootstrap.sh

EXPOSE 9000

CMD ["supervisord"]
