begin
    require 'rake'
    require 'json'
    require 'base64'
    require 'rspec'
    require 'serverspec'
    require 'rspec/retry'
    require 'rspec/core/rake_task'

    RSpec.configure do |config|
        # show retry status in spec process
        config.verbose_retry = true
        # show exception that triggers a retry if verbose_retry is set to true
        config.display_try_failure_messages = true
    end

    RSpec::Core::RakeTask.new(:spec, :pattern, :configuration) do |t, task_args|
        t.pattern = task_args[:pattern]
        t.fail_on_error = true

        $specConfiguration = JSON.parse(Base64.decode64(task_args[:configuration]))

        ENV['DOCKERFILE'] = $specConfiguration['DOCKERFILE']
        ENV['OS_FAMILY'] = $specConfiguration['OS_FAMILY']
        ENV['OS_VERSION'] = $specConfiguration['OS_VERSION']
        ENV['DOCKER_IMAGE'] = $specConfiguration['DOCKER_IMAGE']
        ENV['DOCKER_TAG'] = $specConfiguration['DOCKER_TAG']
    end

rescue LoadError
    # no rspec available
end
