{{ docker.from("base-app", "ubuntu-15.10") }}

{{ docker.copy('conf/', '/opt/docker/') }}

RUN set -x \
    {{ php5.ubuntu14() }} \
    {{ provision.runBootstrap() }} \
    {{ docker.cleanup() }}

{{ docker.expose('9000') }}
