{{ docker.from("php-dev", "debian-7-php7") }}

{{ docker.version() }}

{{ docker.environmentWeb() }}

{{ docker.copy('conf/', '/opt/docker/') }}

{{ apache.debian8('php-apache') }}

{{ docker.expose('80 443') }}
