{{ docker.from("php-apache", "8.1-alpine") }}

{{ environment.web() }}
{{ environment.webPhp() }}
{{ environment.webDevelopment() }}

{{ docker.copy('conf/', '/opt/docker/') }}

RUN set -x \
    {{ php.officialDevelopmentAlpine(version="8.1") }} \
    {{ provision.runBootstrap() }} \
    {{ docker.cleanup() }}
