{{ docker.from("base-app", "centos-7") }}

{{ docker.version() }}

{{ docker.environmentWeb() }}

{{ docker.copy('conf/', '/opt/docker/') }}

{{ php5.webtatic() }}

{{ docker.expose('9000') }}