{{ docker.from("php", "debian-9") }}

{{ docker.version() }}

{{ environment.web() }}
{{ environment.webPhp() }}

{{ docker.copy('conf/', '/opt/docker/') }}

{{ apache.debian9('php-apache') }}

{{ docker.expose('80 443') }}
