{{ docker.from("php-nginx", "8.5") }}

{{ environment.web() }}
{{ environment.webPhp() }}
{{ environment.webDevelopment() }}

{{ docker.copy('conf/', '/opt/docker/') }}

RUN set -x \
    {{ php.officialDevelopment(version="8.5") }} \
    {{ provision.runBootstrap() }} \
    {{ docker.cleanup() }}
