{{ docker.from("php-dev", "debian-8") }}

{{ docker.version() }}

{{ environment.web() }}

{{ docker.copy('conf/', '/opt/docker/') }}

{{ nginx.debian('php-nginx php-nginx-dev') }}

{{ docker.expose('80 443') }}
