{{ docker.from("php", "debian-8") }}

{{ docker.version() }}

{{ docker.environmentWeb() }}

{{ docker.copy('conf/', '/opt/docker/') }}

{{ apache.debian8('php-apache') }}

{{ docker.expose('80 443') }}
