{{ baselayout.dockerStage() }}

{{ docker.fromOfficial("alpine", "3.8") }}

{{ docker.version() }}

{{ environment.general() }}

{{ baselayout.copy() }}

RUN set -x \
    {{ bootstrap.alpine() }} \
    {{ provision.runBootstrap() }} \
    {{ docker.cleanup() }}
