{{ docker.fromOfficial("solr", "6.3.0") }}

{{ docker.version() }}

{{ environment.general(charset="C.UTF-8") }}

COPY ./solr/ /tmp/solr

USER root

RUN rm -rf /opt/solr/server/solr \
    && mv /tmp/solr /opt/solr/server/solr \
    && mkdir -p /opt/solr/server/solr/data \
    && chown -R solr:solr /opt/solr/server/solr/

USER solr

VOLUME ["/opt/solr/server/solr/data"]
