{{ docker.fromOfficial("solr", "6.3.0") }}

{{ docker.version() }}

RUN rm -fR /opt/solr/server/solr/*

COPY ./conf/ /opt/solr/server/solr

USER root

RUN mkdir -p /opt/solr/server/solr/data \
    && chown -R solr:solr /opt/solr/server/solr/

USER solr

VOLUME ["/opt/solr/server/solr/data"]
