{{ base.from("base", "ubuntu-12.04") }}

{{ base.version }}

{{ base.environmentWeb }}

{{ apache.ubuntu12() }}

# Deploy scripts/configurations
COPY conf/ /opt/docker/
RUN bash /opt/docker/bin/control.sh provision.role.bootstrap webdevops-apache \
    && bash /opt/docker/bin/bootstrap.sh

EXPOSE 80 443

CMD ["supervisord"]
