{{ docker.from("bootstrap", "ubuntu-14.04") }}

{{ docker.version() }}

{{ environment.homePath() }}

{{ docker.copy('conf/', '/opt/docker/') }}

{{ base.ubuntu() }}

{{ docker.entrypoint("/opt/docker/bin/entrypoint.sh") }}
{{ docker.cmd("supervisord") }}
