{{ docker.from("php-dev", "ubuntu-14.04") }}

{{ docker.version() }}

{{ environment.web() }}
{{ environment.webPhp() }}
{{ environment.webDevelopment() }}

{{ docker.copy('conf/', '/opt/docker/') }}

{{ apache.ubuntu14('php-apache apache-dev php-dev') }}

{{ docker.expose('80 443') }}
