{{ docker.from("php-dev", "alpine-3-php7") }}

{{ docker.version() }}

{{ environment.web() }}
{{ environment.webPhp() }}

{{ docker.copy('conf/', '/opt/docker/') }}

{{ nginx.alpine('php-nginx php-nginx-dev') }}

{{ docker.expose('80 443') }}
