{{ docker.from("php-nginx", "debian-9") }}

{{ environment.web() }}
{{ environment.webPhp() }}
{{ environment.webDevelopment() }}

{{ docker.copy('conf/', '/opt/docker/') }}

{{ nginx.debian('php-nginx nginx-dev php-dev') }}

{{ docker.expose('80 443') }}
