{{ docker.from("php-dev", "debian-7") }}

{{ docker.version() }}

{{ environment.web() }}
{{ environment.webPhp() }}
{{ environment.webDevelopment() }}

{{ docker.copy('conf/', '/opt/docker/') }}

{{ apache.debian8('php-apache') }}

{{ docker.expose('80 443') }}
