---

APPLICATION_USER:  "{{ lookup('env','APPLICATION_USER') }}"
APPLICATION_GROUP: "{{ lookup('env','APPLICATION_GROUP') }}"
APPLICATION_UID:   "{{ lookup('env','APPLICATION_UID') }}"
APPLICATION_GID:   "{{ lookup('env','APPLICATION_GID') }}"

HTTPD_VARS:
  - variable: DOCUMENT_INDEX
    value:    "{{ lookup('env','WEB_DOCUMENT_INDEX') }}"

  - variable: DOCUMENT_ROOT
    value:    "{{ lookup('env','WEB_DOCUMENT_ROOT') }}"

  - variable: ALIAS_DOMAIN
    value:    "{{ lookup('env','WEB_ALIAS_DOMAIN') }}"

  - variable: SERVERNAME
    value:    "{{ ansible_nodename }}"
