{{ docker.from("php-nginx", "ubuntu-15.04") }}

{{ environment.web() }}
{{ environment.webPhp() }}
{{ environment.webDevelopment() }}

{{ docker.copy('conf/', '/opt/docker/') }}

{{ php5dev.ubuntu() }}
