{{ docker.from("php", "alpine-3") }}

{{ docker.version() }}

{{ docker.environmentWeb() }}

{{ docker.copy('conf/', '/opt/docker/') }}

{{ apache.alpine('php-apache') }}

{{ docker.expose('80 443') }}
