{{ base.from("php", "alpine-3") }}

{{ base.version() }}

{{ base.environmentWeb() }}

{{ apache.alpine() }}

# Deploy scripts/configurations
COPY conf/ /opt/docker/
RUN bash /opt/docker/bin/control.sh provision.role.bootstrap webdevops-apache \
    && bash /opt/docker/bin/control.sh provision.role.bootstrap webdevops-php-apache \
    && bash /opt/docker/bin/bootstrap.sh

EXPOSE 80 443

CMD ["supervisord"]
