{{ docker.from("php", "alpine-php5") }}

{{ environment.web() }}
{{ environment.webPhp() }}

{{ docker.copy('conf/', '/opt/docker/') }}

{{ apache.alpine('php-apache') }}

{{ docker.expose('80 443') }}
