{{ docker.from("php", "7.4-alpine") }}

{{ docker.copy('conf/', '/opt/docker/') }}

RUN set -x \
    {{ php.officialDevelopmentAlpine(version="7.4") }} \
    {{ provision.runBootstrap() }} \
    {{ docker.cleanup() }}
