#++++++++++++++++++++++++++++++++++++++
# Debian 7 Ansible Docker container
#++++++++++++++++++++++++++++++++++++++

FROM webdevops/bootstrap:debian-7
MAINTAINER info@webdevops.io
LABEL vendor=WebDevOps.io
LABEL io.webdevops.layout=4
LABEL io.webdevops.version=0.19.0
