{{ docker.from("php-dev", "centos-7") }}

{{ environment.web() }}
{{ environment.webPhp() }}
{{ environment.webDevelopment() }}

{{ docker.copy('conf/', '/opt/docker/') }}

{{ nginx.centos('php-nginx nginx-dev php-dev') }}

{{ docker.expose('80 443') }}
