{{ docker.from("bootstrap", "centos-7") }}

{{ docker.version() }}

{{ environment.base() }}

{{ docker.copy('conf/', '/opt/docker/') }}

{{ ansible.centos() }}

{{ base.centos() }}

{{ docker.entrypoint("/opt/docker/bin/entrypoint.sh") }}
{{ docker.cmd("supervisord") }}
