{{ docker.from("bootstrap", "centos-7") }}

{{ docker.version() }}

{{ environment.homePath() }}

{{ docker.copy('conf/', '/opt/docker/') }}

{{ base.centos() }}

{{ docker.entrypoint("/opt/docker/bin/entrypoint.sh") }}
{{ docker.cmd("supervisord") }}
