{{ base.from("base", "centos-7") }}

{{ base.version() }}

{{ base.environmentWeb() }}

{{ nginx.centos() }}

# Deploy scripts/configurations
COPY conf/ /opt/docker/
RUN bash /opt/docker/bin/control.sh provision.role.bootstrap webdevops-nginx \
    && bash /opt/docker/bin/bootstrap.sh

EXPOSE 80 443

CMD ["supervisord"]
