#++++++++++++++++++++++++++++++++++++++
# Debian 8 Base Docker container
#++++++++++++++++++++++++++++++++++++++

FROM webdevops/bootstrap:debian-8
MAINTAINER info@webdevops.io
LABEL vendor=WebDevOps.io
LABEL io.webdevops.layout=4
LABEL io.webdevops.version=0.18.0
