{{ baselayout.dockerStage() }}

{{ docker.fromOfficial("php", "7.1-fpm") }}

{{ docker.version() }}

{{ environment.general() }}
{{ environment.base() }}
{{ environment.baseApp() }}

{{ baselayout.copy() }}

{{ docker.copy('conf/', '/opt/docker/') }}

{{ bootstrap.debian('jessie') }}

{{ base.debian() }}

{{ baseapp.debian() }}

{{ php.official(version='7.1') }}

{{ docker.expose('9000') }}
{{ docker.entrypoint("/entrypoint") }}
{{ docker.cmd("supervisord") }}
