{{ docker.from("php", "ubuntu-12.04") }}

{{ docker.version() }}

{{ docker.environmentWeb() }}

{{ docker.copy('conf/', '/opt/docker/') }}

{{ nginx.ubuntu('php-nginx') }}

{{ docker.expose('80 443') }}
