{{ docker.from("php", "debian-9-php7") }}

{{ docker.version() }}

{{ docker.environmentWeb() }}

{{ docker.copy('conf/', '/opt/docker/') }}

{{ apache.debian9('php-apache') }}

{{ docker.expose('80 443') }}
