{{ docker.from("base","latest") }}

# Install services
RUN /usr/local/bin/apt-install \
        liquidsoap \
        liquidsoap-plugin-all \
        mplayer \
        gstreamer0.10-plugins-base \
        gstreamer0.10-plugins-good \
    {{ docker.cleanup() }}

ENV LIQUIDSOAP_USER            "liquidsoap"
ENV LIQUIBASE_TELNET           "1"

ENV LIQUIDSOAP_SCRIPT          "/opt/docker/etc/liquidsoap/default.liq"
ENV LIQUIDSOAP_TEMPLATE        "/opt/docker/etc/liquidsoap/default.liq"

ENV LIQUIBASE_STREAM_INPUT     "http://icecast:8000/live"

ENV LIQUIBASE_PLAYLIST_DEFAULT "audio_to_stereo(single('/opt/docker/etc/liquidsoap/default.mp3'))"

ENV LIQUIBASE_PLAYLIST_DAY     "playlist('/opt/docker/etc/liquidsoap/playlist-day.pls')"
ENV LIQUIBASE_PLAYLIST_DAY_TIMERANGE "4h-2h"

ENV LIQUIBASE_PLAYLIST_NIGHT   "playlist('/opt/docker/etc/liquidsoap/playlist-night.pls')"
ENV LIQUIBASE_PLAYLIST_NIGHT_TIMERANGE "2h-14h"

ENV LIQUIBASE_OUTPUT "output.icecast(%mp3(bitrate=128),host='localhost',port=8000,password='secretpassword',mount='liquidsoap-128',name=META_name,genre=META_genre,url=META_url,description=META_desc,ALL_input)"

ENV LIQUIBASE_META_NAME        "Liquidsoap Docker"
ENV LIQUIBASE_META_GENRE       ""
ENV LIQUIBASE_META_URL         ""
ENV LIQUIBASE_META_DESCRIPTION ""

{{ docker.copy('conf/', '/opt/docker/') }}

{{ docker.cmd("liquidsoap") }}

{{ docker.expose('1234') }}
