{{ docker.from("php-nginx", "alpine-php5") }}

{{ environment.web() }}
{{ environment.webPhp() }}
{{ environment.webDevelopment() }}

{{ docker.copy('conf/', '/opt/docker/') }}

{{ php5dev.alpine() }}
