{{ docker.from("php-nginx", "alpine-php5") }}

{{ environment.web() }}
{{ environment.webPhp() }}
{{ environment.webDevelopment() }}

{{ docker.copy('conf/', '/opt/docker/') }}

{{ nginx.alpine('php-nginx nginx-dev php-dev') }}

{{ docker.expose('80 443') }}
