{{ docker.from("php-dev", "debian-8-php7") }}

{{ docker.version() }}

{{ docker.environmentWeb() }}

{{ docker.copy('conf/', '/opt/docker/') }}

{{ nginx.debian('php-nginx php-nginx-dev') }}

{{ docker.expose('80 443') }}
