{{ docker.from("php", "8.3-alpine") }}

{{ environment.web() }}
{{ environment.webPhp() }}
{{ environment.nginx() }}

{{ docker.copy('conf/', '/opt/docker/') }}

RUN set -x \
    {{ nginx.alpine() }} \
    {{ provision.runBootstrap() }}

{{ docker.expose('80 443') }}
