{{ docker.from("php-apache", "ubuntu-17.04") }}

{{ environment.web() }}
{{ environment.webPhp() }}
{{ environment.webDevelopment() }}

{{ docker.copy('conf/', '/opt/docker/') }}

{{ php7dev.ubuntu() }}
