{{ docker.from("hhvm", "ubuntu-16.04") }}

{{ docker.version() }}

{{ environment.web() }}
{{ environment.webPhp() }}

{{ docker.copy('conf/', '/opt/docker/') }}

{{ apache.ubuntu16(role='hhvm-apache') }}

{{ docker.expose('80 443') }}
