{{ docker.from("php-dev", "ubuntu-16.04") }}

{{ docker.version() }}

{{ docker.environmentWeb() }}

{{ docker.copy('conf/', '/opt/docker/') }}

{{ nginx.ubuntu('php-nginx php-nginx-dev') }}

{{ docker.expose('80 443') }}
