#!/usr/bin/env php
<?php
// application.php

require __DIR__ . '/vendor/autoload.php';

use Symfony\Component\Console\Application;
use Webdevops\Build\Commands\GitlabCommand;

$application = new Application();

// ... register commands
$application->add(new GitlabCommand());

$application->run();
