#!/usr/bin/env php
<?php
// application.php

require __DIR__ . '/vendor/autoload.php';

use Symfony\Component\Console\Application;
use Webdevops\Build\Commands\GithubCommand;

$application = new Application();

// ... register commands
$application->add(new GithubCommand());

$application->run();
