{{ docker.from("php", "8.5") }}

{{ docker.copy('conf/', '/opt/docker/') }}

RUN set -x \
    {{ php.officialDevelopment(version="8.5") }} \
    {{ provision.runBootstrap() }} \
    {{ docker.cleanup() }}
