#++++++++++++++++++++++++++++++++++++++
# Ubuntu 12.04 Ansible Docker container
#++++++++++++++++++++++++++++++++++++++

FROM webdevops/bootstrap:ubuntu-12.04
MAINTAINER info@webdevops.io
LABEL vendor=WebDevOps.io
LABEL io.webdevops.layout=4
LABEL io.webdevops.version=0.19.0
