{{ docker.from("php-dev", "alpine-3-php7") }}

{{ docker.version() }}

{{ docker.environmentWeb() }}

{{ docker.copy('conf/', '/opt/docker/') }}

{{ apache.alpine('php-apache') }}

{{ docker.expose('80 443') }}
