{{ docker.from("bootstrap", "debian-7") }}

{{ docker.version() }}

{{ docker.environmentHomePath() }}

{{ docker.copy('conf/', '/opt/docker/') }}

{{ base.debian() }}

{{ docker.entrypoint("/opt/docker/bin/entrypoint.sh") }}
{{ docker.cmd("supervisord") }}
