{{ docker.from("php-dev", "alpine-3") }}

{{ docker.version() }}

{{ environment.web() }}
{{ environment.webPhp() }}
{{ environment.webDevelopment() }}

{{ docker.copy('conf/', '/opt/docker/') }}

{{ nginx.alpine('php-nginx nginx-dev') }}

{{ docker.expose('80 443') }}
