{{ docker.from("php-dev", "alpine-3") }}

{{ docker.version() }}

{{ docker.environmentWeb() }}

{{ docker.copy('conf/', '/opt/docker/') }}

{{ nginx.alpine('php-nginx') }}

{{ docker.expose('80 443') }}
