{{ docker.from("php-apache", "7.0") }}

{{ environment.web() }}
{{ environment.webPhp() }}
{{ environment.webDevelopment() }}

{{ docker.copy('conf/', '/opt/docker/') }}

{{ php.officialDevelopment(version="7.0") }}
