{{ docker.from("php-nginx", "ubuntu-14.04") }}

ENV WEB_DOCUMENT_ROOT  /app/piwik/
ENV PIWIK_URL          http://example.com/

{{ docker.copy('conf/', '/opt/docker/') }}

# Deploy scripts/configurations
COPY conf/ /opt/docker/
RUN /opt/docker/bin/provision add --tag bootstrap --tag entrypoint --tag onbuild webdevops-piwik \
    && /opt/docker/bin/control.sh service.enable cron \
    && /opt/docker/bin/bootstrap.sh

ONBUILD RUN /opt/docker/bin/bootstrap.sh onbuild
ONBUILD VOLUME /app
