{{ docker.from("php-dev", "ubuntu-16.04") }}

{{ docker.version() }}

{{ environment.web() }}

{{ docker.copy('conf/', '/opt/docker/') }}

{{ apache.ubuntu16('php-apache') }}

{{ docker.expose('80 443') }}
