{{ docker.from("bootstrap", "debian-9") }}

{{ docker.version() }}

{{ environment.base() }}

{{ docker.copy('conf/', '/opt/docker/') }}

{{ ansible.debian() }}

{{ base.debian() }}

{{ docker.entrypoint("/opt/docker/bin/entrypoint.sh") }}
{{ docker.cmd("supervisord") }}
