{{ docker.from("php", "ubuntu-16.10") }}

{{ docker.version() }}

{{ environment.web() }}
{{ environment.webPhp() }}

{{ docker.copy('conf/', '/opt/docker/') }}

{{ apache.ubuntu16('php-apache') }}

{{ docker.expose('80 443') }}
