{{ base.from("hhvm", "ubuntu-14.04") }}

{{ base.version() }}

{{ base.environmentWeb() }}

{{ nginx.ubuntu() }}

# Deploy scripts/configurations
COPY conf/ /opt/docker/
RUN bash /opt/docker/bin/control.sh provision.role.bootstrap webdevops-nginx \
    && bash /opt/docker/bin/control.sh provision.role.bootstrap webdevops-hhvm-nginx \
    && bash /opt/docker/bin/bootstrap.sh

EXPOSE 80 443

CMD ["supervisord"]
