{{ docker.from("php-dev", "ubuntu-12.04") }}

{{ docker.version() }}

{{ environment.web() }}
{{ environment.webPhp() }}
{{ environment.webDevelopment() }}

{{ docker.copy('conf/', '/opt/docker/') }}

{{ apache.ubuntu12('php-apache apache-dev') }}

{{ docker.expose('80 443') }}
