{{ docker.from("bootstrap", "alpine-3") }}

{{ docker.version() }}

{{ docker.environmentHomePath() }}

{{ docker.copy('conf/', '/opt/docker/') }}

{{ base.alpine() }}

{{ docker.entrypoint("/opt/docker/bin/entrypoint.sh") }}
{{ docker.cmd("supervisord") }}
