{{ docker.from("php", "centos-7-php56") }}

{{ docker.version() }}

{{ environment.web() }}
{{ environment.webPhp() }}

{{ docker.copy('conf/', '/opt/docker/') }}

{{ apache.centos('php-apache') }}

{{ docker.expose('80 443') }}
