{{ docker.from("php-dev", "ubuntu-15.10") }}

{{ docker.version() }}

{{ environment.web() }}
{{ environment.webPhp() }}

{{ docker.copy('conf/', '/opt/docker/') }}

{{ nginx.ubuntu('php-nginx php-nginx-dev') }}

{{ docker.expose('80 443') }}
