{{ docker.from("php-nginx", "ubuntu-15.10") }}

{{ environment.web() }}
{{ environment.webPhp() }}
{{ environment.webDevelopment() }}

{{ docker.copy('conf/', '/opt/docker/') }}

{{ nginx.ubuntu('php-nginx nginx-dev php-dev') }}

{{ docker.expose('80 443') }}
