{{ docker.from("postfix") }}

{{ docker.version() }}

{{ docker.environmentMailbox() }}

{{ docker.copy('conf/', '/opt/docker/') }}

{{ mailsandbox.ubuntu() }}

{{ docker.expose('25 465 587 143 993') }}
