{{ docker.from("bootstrap", "alpine") }}

{{ environment.base() }}

{{ docker.copy('conf/', '/opt/docker/') }}

{{ ansible.alpine() }}

{{ base.alpine() }}

{{ docker.entrypoint("/entrypoint") }}
{{ docker.cmd("supervisord") }}
