{{ docker.fromOfficial("java") }}

{{ docker.version() }}

{{ environment.liquibase('3.5.3', 'org.postgresql.Driver', '/usr/share/java/postgresql.jar') }}

{{ docker.copy('conf/', '/opt/docker/') }}

{{ liquibase.postgres() }}

{{ docker.entrypoint("/opt/docker/bin/entrypoint.sh") }}

