{{ docker.fromOfficial("java") }}

{{ docker.version() }}

{{ environment.liquibase('3.5.3', 'org.postgresql.Driver', '/usr/share/java/postgresql.jar') }}

{{ docker.copy('conf/', '/opt/docker/') }}

RUN set -x \
    {{ liquibase.postgres() }} \
    {{ provision.runBootstrap() }} \
    {{ docker.cleanup() }}

{{ docker.workdir("/liquibase") }}
{{ docker.entrypoint("/entrypoint") }}

