{{ docker.from("hhvm", "ubuntu-16.04") }}

{{ environment.web() }}
{{ environment.webPhp() }}

{{ docker.copy('conf/', '/opt/docker/') }}

{{ nginx.ubuntu(role='hhvm-nginx') }}

{{ docker.expose('80 443') }}
